Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MenShoe.EF;
using PagedList.Mvc;
using PagedList;


namespace MenShoe.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        MenShoeEntities db = new MenShoeEntities();

        // GET: Admin/User
        public ActionResult Index(int? page)
        {
            if(Session["IdAdmin"] == null)
            {
                return RedirectToAction("Error","Error");
            }

            int pageSize = 10;
            int pageNumber = page ?? 1;
            return View(db.Users.OrderBy(u=>u.Name).ToPagedList(pageNumber, pageSize));
        }

        /*
        * Detail user
        */

        public ActionResult DetailUser(string id)
        {
            User us = db.Users.FirstOrDefault(u => u.UserID.ToString() == id);
            if(us == null)
            {
                return RedirectToAction("Error","Error");
            }
            return View(us);
        }

        [HttpPost]
        public ActionResult UpdateUser(FormCollection f)
        {
            string username = f["UserName"].ToString();
            User us = db.Users.FirstOrDefault(u => u.UserName == username);
            if(us == null)
            {
                return RedirectToAction("Error", "Error");
            }

            us.Name = f["Name"].ToString();
            us.Email = f["Email"].ToString();
            us.Address = f["Address"].ToString();
            us.Mobile = f["Mobile"].ToString();
            us.Status = bool.Parse(f["status"]);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteUser(string ID)
        {
            User us = db.Users.FirstOrDefault(u => u.UserID.ToString() == ID);
            if(us == null)
            {
                return RedirectToAction("Error","Error");
            }

            db.Users.Remove(us);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/User/UserLogin.cshtml
@model MenShoe.EF.User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>User Login</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
</head>
<body>

    <div class="container">
        @using (Html.BeginForm("UserLogin", "User"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                    </div>
                    <div style="padding-top:30px" class="panel-body">
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                        <form id="loginform" class="form-horizontal" role="form">

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" , @placeholder = "username or email" } })
                                @Html.ValidationMessageFor(model => model.UserName, null, new { @class = "validatelogin" })
                            </div>

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control", @placeholder = "password" })
                                @Html.ValidationMessageFor(model => model.Password, null, new { @class = "validatelogin" })
                            </div>


                            <div class="input-group">
                                <div class="checkbox">
                                    <label>
                                        <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                    </label>
                                </div>
                            </div>

                            <div style="margin-top:10px;" >
                                <!-- Button -->
                                <div class="col-sm-12 controls form-group">
                                    <button class="btn btn-success" type="submit">Login</button>
                                    <a id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</a>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12 control">
                                    <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                                        Don't have an account!
                                        <a href="@Url.Action("UserRegister","User")" >
                                            Sign Up Here
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        }

    </div>


</body>
</html>

Views/User/UserRegister.cshtml
@model MenShoe.EF.User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>User Register</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
</head>
<body>

    <div class="container">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div id="signupbox" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Sign Up</div>
                        <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="@Url.Action("UserLogin","User")">Sign In</a></div>
                    </div>
                    <div class="panel-body">
                        <form id="signupform" class="form-horizontal" role="form">

                            <div id="signupalert" style="display:none" class="alert alert-danger">
                                <p>Error:</p>
                                <span></span>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="UserName" class="col-md-3 control-label">User Name</label>
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "User Name" } })
                                    @Html.ValidationMessageFor(model => model.UserName, null, new { @class = "validatelogin" })
                                    @*<input type="text" class="form-control" name="email" placeholder="Email Address">*@
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="Email" class="col-md-3 control-label">Email</label>
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email Address"} })
                                    @Html.ValidationMessageFor(model => model.Email, null, new { @class = "validatelogin" })
                                    @*<input type="text" class="form-control" name="firstname" placeholder="First Name">*@
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="Name" class="col-md-3 control-label">Name</label>
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                                    @Html.ValidationMessageFor(model => model.Name, null, new { @class = "validatelogin" })
                                    @*<input type="text" class="form-control" name="lastname" placeholder="Last Name">*@
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="Mobile" class="col-md-3 control-label">Mobile</label>
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mobile" } })
                                    @Html.ValidationMessageFor(model => model.Mobile, null, new { @class = "validatelogin" })
                                    @*<input type="password" class="form-control" name="passwd" placeholder="Password">*@
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="Address" class="col-md-3 control-label">Address</label>
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address" } })
                                    @Html.ValidationMessageFor(model => model.Address, null, new { @class = "validatelogin" })
                                    @*<input type="text" class="form-control" name="icode" placeholder="">*@
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="Password" class="col-md-3 control-label">Password</label>
                                <div class="col-md-9">
                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @placeholder = "Password" } )
                                    @Html.ValidationMessageFor(model => model.Password, null, new { @class = "validatelogin" })
                                    @*<input type="text" class="form-control" name="icode" placeholder="">*@
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="ConfirmPassword" class="col-md-3 control-label">Password again</label>
                                <div class="col-md-9">
                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @placeholder = "Password again" } )
                                    @Html.ValidationMessageFor(model => model.Password, null, new { @class = "validatelogin" })
                                    @*<input type="text" class="form-control" name="icode" placeholder="">*@
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <!-- Button -->
                                <div class="col-md-offset-3 col-md-9">
                                    <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Sign Up</button>
                                    <span style="margin-left:8px;">or</span>
                                </div>
                            </div>

                            <div style="border-top: 1px solid #999; padding-top:20px" class="form-group col-md-12">

                                <div class="col-md-offset-3 col-md-9">
                                    <button id="btn-fbsignup" type="button" class="btn btn-primary"><i class="icon-facebook"></i>   Sign Up with Facebook</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>

</body>
</html>