Controllers/ProductCategoryController.cs
using MenShoe.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace MenShoe.Controllers
{
    public class ProductCategoryController : Controller
    {
        MenShoeEntities db = new MenShoeEntities();
        // GET: ProductCategory
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductCategory(int? page, string ProductCategoryID)
        {
            if(string.IsNullOrEmpty(ProductCategoryID))
            {
                return RedirectToAction("Error","Error");
            }
            int pageSize = 18;
            int pageNumber = page ?? 1;
            ViewBag.ProductCategories = db.ProductCategories.ToList();
            ViewBag.Categories = db.Categories.Take(5).ToList();
            ProductCategory pC = db.ProductCategories.SingleOrDefault(p => p.ProductCategoryID.ToString() == ProductCategoryID);
            if(pC == null)
            {
                return RedirectToAction("Error","Error");
            }
            PagedList.IPagedList<Product> lstProduct = db.Products.Where(p=>p.ProductCategoryID.ToString() == ProductCategoryID).OrderBy(p=>p.Price).ToPagedList(pageNumber,pageSize);
            if(lstProduct.Count() ==0)
            {
                return RedirectToAction("EmptyProductCategory");
            }

            ViewBag.ProductCategoryName = pC.Name;
            return View(lstProduct);
        }


        public  ViewResult ListProductCategory()
        {
            List<ProductCategory> lstProductCategory = db.ProductCategories.ToList();
            return View(lstProductCategory);
        }
        
        public ViewResult EmptyProductCategory()
        {

            ViewBag.ProductCategories = db.ProductCategories.ToList();
            ViewBag.Categories = db.Categories.Take(5).ToList();
            return View();
        }
    }
}

Controllers/ProductController.cs
using MenShoe.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MenShoe.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        MenShoeEntities db = new MenShoeEntities();

        public ActionResult DetailProduct(string m_ProductID)
        {
            List<Product_Size> lstProductSize = db.Product_Size.Where(p => p.ProductID.ToString() == m_ProductID).ToList();

            //Check product quanlity
            if (lstProductSize.Count() == 0)
            {
                return RedirectToAction("Error", "Error");
            }
            //get list category and product category
            ViewBag.ProductCategories = db.ProductCategories.ToList();
            ViewBag.Categories = db.Categories.Take(5).ToList();
            Product prd = db.Products.SingleOrDefault(p => p.ProductID.ToString() == m_ProductID);

            //get list image and size, color
            List<ProductImage> lstProductImage = db.ProductImages.Where(p => p.ProductID.ToString() == m_ProductID).ToList();
            Product_Color ProductColor = db.Product_Color.FirstOrDefault(p => p.ProductID.ToString() == m_ProductID);
            ViewBag.lstProductSize = lstProductSize;
            ViewBag.lstProductImage = lstProductImage;
            ViewBag.ProductColor = ProductColor;

            if (prd == null)
            {
                return RedirectToAction("Error","Error");
            }
            // return PartialView("../Product/View_ccdatvoday?m_ProductID=" + m_ProductID + "&sizes=" + iSize + "");
            return View(prd);
        }

        public PartialViewResult HotProductPartial()
        {
            List<Product> lstProduct = db.Products.Take(3).ToList();
            return PartialView(lstProduct);
        }
        
    }
}

Views/ProductCategory/EmptyProductCategory.cshtml
@{
    ViewBag.Title = "EmptyProductCategory";
    Layout = "~/Views/Shared/_UserLayoutDetail.cshtml";
}

<div class="product-box no-mg">

    <h1 class="title clearfix"><span>Not Found</span></h1>
    <div class="alert alert-warning" role="alert">0 items matched.</div>
    @using (Html.BeginForm("Index", "Home"))
    {
        <button type="submit" class="btn btn-success">Back Home</button>
    }
   
</div>

Views/ProductCategory/ListProductCategory.cshtml
@using MenShoe.EF;
@model List<ProductCategory>
@{
    Layout = null;
}

<div class="box-sale-policy" ng-controller="moduleController" ng-init="initSalePolicyController('Shop')">
    <h3><span>Brand</span></h3>
    <div class="sale-policy-block">
        <ul>
            @foreach(var item in Model)
            {
                <li style="clear:both; list-style-type: none;list-style:none"><a style="color:#3c3f44;" href="@Url.Action("ProductCategory","ProductCategory", new { @ProductCategoryID = item.ProductCategoryID })">@item.Name</a></li>
            }
        </ul>
    </div>
    
</div>

Views/ProductCategory/ProductCategory.cshtml
@using MenShoe.EF;
@using PagedList.Mvc;
@model PagedList.IPagedList<MenShoe.EF.Product>
@{
    ViewBag.Title = "ProductCategory";
    Layout = "~/Views/Shared/_UserLayoutDetail.cshtml";
}
<section class="product-content clearfix">
    <h1 class="title clearfix"><span>Men's @ViewBag.ProductCategoryName Shoes</span></h1>
    <nav class="navbar navbar-default product-filter">
        <ul class="display">
            <li id="grid" class="active grid"><a href="#" title="Grid"><i class="fa fa-th-large"></i></a></li>
            <li id="list" class="list"><a href="#" title="List"><i class="fa fa-th-list"></i></a></li>
        </ul>
        <div class="limit">
            <span>Sản phẩm/trang</span>
            <select id="lblimit" name="lblimit" class="nb_item" onchange="window.location.href = this.options[this.selectedIndex].value">
                <option value="?limit=10">10</option>
                <option value="?limit=12">12</option>
                <option value="?limit=20">20</option>
                <option value="?limit=50">50</option>
                <option value="?limit=100">100</option>
                <option value="?limit=250">250</option>
                <option value="?limit=500">500</option>
            </select>
        </div>
        <div class="sort">
            <span>Sắp xếp</span>
            <select class="selectProductSort" id="lbsort" onchange="window.location.href = this.options[this.selectedIndex].value">
                <option value="?sort=index&amp;order=asc">Mặc định</option>
                <option value="?sort=price&amp;order=asc">Gi&#225; tăng dần</option>
                <option value="?sort=price&amp;order=desc">Gi&#225; giảm dần</option>
                <option value="?sort=name&amp;order=asc">T&#234;n sản phẩm: A to Z</option>
                <option value="?sort=name&amp;order=desc">T&#234;n sản phẩm: Z to A</option>
            </select>
        </div>
    </nav>
    <div class="product-block product-grid clearfix">
        @foreach (var item in Model)
        {
            <div class="col-md-2 col-sm-2 col-xs-12 product-resize product-item-box">
                <div class="product-item">
                    <div class="image image-resize">
                        <a href="@Url.Action("DetailProduct","Product", new {@m_ProductID = item.ProductID })" title="Asus TP550LA-CJ040H - Core i3 4030U / 15.6&quot; Touch / 4GB (Đen)">
                            <img src="../@Url.Content(item.Image)" data-original="@Url.Content(item.Image)" alt="@item.ProductID" class="img-responsive lazy-img" />
                        </a>
                        <span class="hot">Hot</span>
                    </div>
                    <div class="right-block">
                        <h2 class="name">
                            <b>@item.ProductCategory.Name.ToUpper()</b>
                            @if (item.Name.Length < 17)
                            {
                                <a href="@Url.Action("DetailProduct","Product", new {@m_ProductID = item.ProductID })" title="@item.Name.ToUpper()">@item.Name.ToUpper()</a>
                            }
                            else
                            {
                                <a href="@Url.Action("DetailProduct","Product", new {@m_ProductID = item.ProductID })" title="@item.Name.ToUpper()">@item.Name.ToUpper().Substring(0, 17)..</a>
                            }
                        </h2>
                        <div class="rating">
                            <div class="rating-1">
                                <span class="rating-img">
                                </span>
                            </div>
                        </div>
                        <div class="price">
                            <span class="price-new">@Convert.ToInt64(item.Price).ToString("####,####") <b>$</b></span>
                        </div>
                        <div class="button">
                            <a class="btn btn-default btn-add-cart" href="@Url.Action("DetailProduct","Product", new { @m_ProductID = item.ProductID, @strURL = Request.Url.ToString() })">View</a>
                        </div>
                    </div>
                </div>
            </div>

        }

        <div class="navigation col-md-12 col-sm-12 col-xs-12">
            <ul class="pagination">
                <li>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</li>
                <li class="">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
                </li>
            </ul>
        </div>
    </div>
    </section>

Views/ProductCategory/ProductCategoryPartial.cshtml
@{
    List<MenShoe.EF.Category> lstCategories = ViewBag.Categories;
    List<MenShoe.EF.ProductCategory> lstProductCategories = ViewBag.ProductCategories;
}
<div class="col-md-3">
    <div class="menu-cate menu-quick-select">
        <div class="menu-cate-title">
            <span><i class="fa fa-th-list"></i><a href="/san-pham.html">CATEGORIES</a></span>
            <i class="fa fa-chevron-circle-down"></i>
        </div>
        <ul class="menu-cate-content">
            <li>
                @{
                    foreach (var C in lstCategories)
                    {
                        <a href="@Url.Action("Category","Category", new { @CategoryID = C.CategoryID })"><i class="fa "></i>@C.Name<span class="arrow-menu"><i class="fa fa-chevron-right "></i></span></a>
                    }
                    <a href=""><i class="fa "></i>VIEW ALL<span class="arrow-menu"><i class="fa fa-chevron-right "></i></span></a>
                }

                <div class="sub-menu hidden-xs">
                    <ul class="colum0">
                        <li>
                            <a href="/san-pham/may-quay-phim">BRAND</a>
                            <ul class="subview-menu">
                                @{
                                    foreach (var prd in lstProductCategories)
                                    {
                                        <li><a href="@Url.Action("ProductCategory","ProductCategory", new { @ProductCategoryID = prd.ProductCategoryID })">@prd.Name</a></li>
                                    }
                                }
                            </ul>
                        </li>
                        <li>
                            <a href="/san-pham/may-anh-so-1140">M&#225;y ảnh số</a>
                            <ul class="subview-menu">
                                <li><a href="/san-pham/may-anh-canon">M&#225;y ảnh Canon</a></li>
                                <li><a href="/san-pham/may-anh-panasonic">M&#225;y ảnh Panasonic</a></li>
                                <li><a href="/san-pham/may-anh-samsung">M&#225;y ảnh Samsung</a></li>
                                <li><a href="/san-pham/may-anh-sony">M&#225;y ảnh Sony</a></li>
                                <li><a href="/san-pham/may-anh-nikon">M&#225;y ảnh Nikon</a></li>
                                <li><a href="/san-pham/may-anh-casio-1411">M&#225;y ảnh Casio</a></li>
                            </ul>
                        </li>
                    </ul>
                    @*<ul class="colum1">
                            <li>
                                <a href="/san-pham/bo-do-the-thao-nam-1139">Bộ Đồ Thể Thao Nam</a>
                            </li>
                            <li>
                                <a href="/san-pham/phu-kien">Phụ kiện</a>
                                <ul class="subview-menu">
                                    <li><a href="/san-pham/chan-may">Ch&#226;n m&#225;y</a></li>
                                    <li><a href="/san-pham/pin--sac">Pin, Sạc</a></li>
                                    <li><a href="/san-pham/the-nho">Thẻ nhớ</a></li>
                                    <li><a href="/san-pham/lens-hood">Lens hood</a></li>
                                    <li><a href="/san-pham/bo-ve-sinh">Bộ vệ sinh</a></li>
                                </ul>
                            </li>
                        </ul>*@
                </div>
            </li>
        </ul>
    </div>
    @*<script>
        $(document).ready(function () {
            var $colls = $('.menu-cate-title'),
                $menulist = $(".menu-cate-content"),
                $menuitems = $menulist.find('li');

            $menulist.hide();


            var hoverin = function () {
                $menulist.fadeIn();
            };

            var hoverout = function () {
                $menulist.fadeOut();
            };

            var collenter = function () {
                $menuitems.fadeIn();
            };

            $menulist
                .hover(collenter, hoverout)
                .bind('mouseleave', hoverout);

            $colls.bind('mouseenter', hoverin);
        });
    </script>*@
</div>